In [1]:
import utils
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split

**Reading the data**

In [2]:
train_df = pd.read_csv('data/train_data.csv')
train_df.head()

,title,link,domain,published_date,topic
0,NSW remains on COVID-19 high alert | The Star ...,https://www.newcastlestar.com.au/story/6878465...,newcastlestar.com.au,2020-08-13 17:32:28,HEALTH
1,Missing people: How does someone just disappear?,https://www.bbc.co.uk/news/uk-england-cambridg...,bbc.co.uk,2020-08-04 15:56:20,NATION
2,"An American Pickle review: In a dual role, Set...",https://www.polygon.com/2020/8/6/21357120/amer...,polygon.com,2020-08-06 15:58:22,ENTERTAINMENT
3,Katie Spotz to Run 130 Miles to Bring Clean Wa...,http://www.christianitydaily.com/articles/9647...,christianitydaily.com,2020-08-07 19:45:00,NATION
4,CDC Director Says This Fall Could Be ‘the Wors...,https://www.self.com/story/worst-fall-ever-covid,self.com,2020-08-13 19:37:52,HEALTH

In [10]:
test_df = pd.read_csv('data/test_data.csv')
test_df.head()

,title,link,domain,published_date,topic
0,"Easy, Efficient Way to Sanitize N95 Masks Usin...",https://scitechdaily.com/easy-efficient-way-to...,scitechdaily.com,2020-08-08 04:02:48,HEALTH
1,Child sleep problems associated with impaired ...,https://www.eurekalert.org/pub_releases/2020-0...,eurekalert.org,2020-08-03 16:56:38,HEALTH
2,"Guide to the Classics: Boccaccio's Decameron, ...",https://theconversation.com/guide-to-the-class...,theconversation.com,2020-08-11 20:12:00,ENTERTAINMENT
3,"The Ecstatic, Violent Joy of Susan Choi’s My E...",https://www.vulture.com/2020/08/raven-leilani-...,vulture.com,2020-08-04 12:00:00,ENTERTAINMENT
4,Why iPhone 12 Will Be Another 'Defining Chapte...,https://allafrica.com/stories/202008140183.html,allafrica.com,2020-08-14 06:58:33,BUSINESS

**Checking the ratio of training as well as test dataset**

**Percentage of training dataset**

In [12]:
train_df.topic.value_counts(normalize = True).sort_index().mul(100).round(1).astype(str) + '%'

topic
BUSINESS         13.2%
ENTERTAINMENT    14.1%
HEALTH           15.1%
NATION           13.2%
SCIENCE           0.7%
SPORTS           13.6%
TECHNOLOGY       15.3%
WORLD            14.8%
Name: proportion, dtype: str

**Percentage of test dataset**

In [13]:
test_df.topic.value_counts(normalize = True).sort_index().mul(100).round(1).astype(str) + '%'

topic
BUSINESS         15.9%
ENTERTAINMENT    12.7%
HEALTH            9.3%
NATION           15.9%
SCIENCE          13.2%
SPORTS           14.3%
TECHNOLOGY        8.6%
WORLD            10.1%
Name: proportion, dtype: str

**As we can see that, the data distribution of the topics among training and test dataset is unbalanced**
**So we must split the data in such that the training and test dataset has nearly balanced or balanced distribution of all the topics**

In [17]:
total_df = pd.concat([train_df,test_df],ignore_index = True)  #merging the training as well as test dataset
total_df.shape

(108774, 5)

**Splitting of the dataset**

In [ ]:
# Splitting the combined dataset to 60% train, 20% dev, and 20% test set inorder to produce a balanced split along the `topic` column.
train_df, test_df = train_test_split(total_df,test_size = 0.2)
train_df, dev_df = train_test_split(total_df,test_size = 0.2)